= GoSecure's Presentation Material
:title: GoSecure's Presentation Material
:linkcss!:
:sectids!:
:twob: https://twitter.com/obilodeau
:twpa: https://twitter.com/h3xstream
:twmcpc: https://twitter.com/MasarahClouston
:twtd: https://twitter.com/nyx__o
:twhg: https://twitter.com/hugospns
:lnlc: https://linkedin.com/in/lillygosec
:twib: https://twitter.com/Corb3nik
:twml: https://twitter.com/marc_etienne_

Botconf 2016::

  * https://www.botconf.eu/wp-content/uploads/2016/11/PR08-MOOSE-BILODEAU-PAQUET-CLOUSTON.pdf[
    Attacking Linux/Moose 2.0 Unraveled an EGO MARKET]
    by link:{twmcpc}[Masarah Paquet-Clouston] and link:{twob}[Olivier Bilodeau]

HackFest 2016::

  * https://docs.google.com/presentation/d/18y60Xy0eVeUnBXIH_t3ikfly_uyYbtfI6zAuKCHtlac/edit?usp=sharing[
    Abusing PHP 7's OPcache to Spawn Webshells]
    by link:{twib}[Ian Bouchard]
    [ https://www.youtube.com/watch?v=yLpsIWh7rvU[video] ]

BlackHat Europe 2016::

  * https://www.blackhat.com/docs/eu-16/materials/eu-16-Paquet-Clouston-Ego-Market_When-Greed-for-Fame-Benefits-Large-Scale-Botnets.pdf[
    EGO MARKET: When Greed For Fame Benefits Large-Scale Botnets]
    by link:{twmcpc}[Masarah Paquet-Clouston] and link:{twob}[Olivier Bilodeau]
    [ https://www.youtube.com/watch?list=PLH15HpR5qRsXcnfTOLOA3yYSd0CmYwOHS&v=9pmKj0P9_ow[video],
    http://gosecure.net/2016/11/02/exposing-the-ego-market-the-cybercrime-performed-by-the-linux-moose-botnet/[blog post],
    http://gosecure.net/wp-content/uploads/2016/11/Ego-Market_When-Greed-for-Fame-Benefits-Large-Scale-Botnets.pdf[paper]
    ]

44Con 2016::

  * Workshop: Hunting Linux Malware for Fun and $flags
    by link:{twml}[Marc-Etienne M.Léveillé] and link:{twob}[Olivier Bilodeau] [ https://videos.44con.com/187676320[video] ]
  * Workshop: Advanced Java Application Code Review
    by link:{twpa}[Philippe Arteau] [ https://videos.44con.com/187676319[video] ]
  * Malboxes Lightning Talk (22 minutes)
    by link:{twob}[Olivier Bilodeau] [ https://videos.44con.com/185322203[video] ]

NorthSec 2016::

  * link:2016-05-19_northsec/malboxes.html[Applying DevOps Principles for Better Malware Analysis]
    by link:{twob}[Olivier Bilodeau] and link:{twhg}[Hugo Genesse]
    [ https://www.youtube.com/watch?v=rfmUcYGGrls[video],
    link:2016-05-19_northsec/OlivierBilodeau_HugoGenesse-Malboxes.pdf[PDF] ]

AtlSecCon April 2016::

  * https://speakerdeck.com/lillypad/pe-file-structure-security-and-custom-base-64-steganography[Enumerating
    PE File Structure Security Protections and Custom Base 64 Steganography]
    by link:{lnlc}[Lilly Chalupowski] [
    link:2016-04-07_atlseccon/PE_File_Security.pdf[PDF],
    https://github.com/lillypad/badger[Badger project],
    https://github.com/lillypad/chameleon[Chameleon project]
    ]

  * link:2016-04-07_atlseccon/internet-of-threats.html[Internet of {Things,Threats}]
    by link:{twob}[Olivier Bilodeau] and ESET's link:{twtd}[Thomas Dupuy]
    [ link:2016-04-07_atlseccon/OlivierBilodeau_ThomasDupuy-Internet_of_Threats.pdf[PDF] ]

  * https://docs.google.com/presentation/d/1yZWsLSgrOYJjeQwJWXUckvLi0hFyvPry-x1DgR_P30g/preview[The
    new wave of Deserialization Bugs] by link:{twpa}[Philippe Arteau]

Confoo February 2016::

  * https://docs.google.com/presentation/d/130n98LMDyD1xyZp5wzgmjmrZPP-nBcU9tI3NaOVfBs0/preview[Modern
    XSS: Protections (and bypasses)] by link:{twpa}[Philippe Arteau]
    [ https://github.com/GoSecure/presentations/tree/master/2016-02-24_confoo/demos[Demos] ]

OWASP Montreal January 2016::

  * link:2016-01-20_owasp-mtl/internet-of-threats.html[Internet of {Things,Threats}]
    by link:{twob}[Olivier Bilodeau] and ESET's link:{twtd}[Thomas Dupuy]
    [ link:2016-01-20_owasp-mtl/internet-of-threats.pdf[PDF] ]

NOTE: PDFs are a degraded experience over the linked (HTML) slide decks.
